heat_template_version: 2013-05-23
description: >
  A simple Heat template to deploy CoreOS into an existing cluster.
parameters:
  network_id:
    type: string
    label: Network ID
    description: ID of existing Neutron network to use
#    default: <ID of Neutron network to which instances should connect>
    default: 8ec9e3c3-c968-4337-9948-086b08086a1d
  image_id:
    type: string
    label: Glance Image ID
    description: ID of existing Glance image to use
#    default: <ID of CoreOS Glance image>
    default: 36d254d6-a729-44ef-b292-cbb7d4d980d1
resources:
  instance0_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_param: network_id }
#      security_groups:
#        - <ID of security group to apply to this Neutron port>
#        - default
  instance0:
    type: OS::Nova::Server
    properties:
      name: coreos-04
      image: { get_param: image_id }
      flavor: m1.small
      networks:
        - port: { get_resource: instance0_port0 }
#      key_name: <Name of SSH key to inject into CoreOS instance>
      key_name: river-key-pair
      user_data_format: RAW
      user_data: |
        #cloud-config
        write_files:
          - path: /etc/systemd/system/docker.service.d/http-proxy.conf
            owner: core:core
            permissions: 0644
            content: |
              [Service]
              Environment="HTTP_PROXY=http://10.110.15.60:8080"
        coreos:
          etcd:
            discovery: https://discovery.etcd.io/673cfda37383b14fa42fd21a482ce058
            addr: $private_ipv4:4001
            peer-addr: $private_ipv4:7001
          units:
            - name: etcd.service
              command: start
            - name: fleet.service
              command: start
            - name: docker.service
              command: restart
