heat_template_version: 2013-05-23

description: Template that installs a simple test server.

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
#    default: trusty-server-cloudimg-amd64
    default: ff5f7be8-4485-4c98-9299-d3675342e1da
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small
  key_pair:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
#    default: my_key
    default: river-key-pair
  public_network:
    type: string
    label: Public network name or ID
    description: Public network to attach server to.
#    default: public
    default: 932975db-3afc-40d7-92c1-40f48c7948ef
  proxy_ip_port:
    type: string
    description: Firewall proxy
    default: 10.110.15.60:8080
  cidr:
    type: string
    label: CIDR
    description: The CIDR of the private network.
    default: '10.10.10.0/24'
  dns_list:
    type: comma_delimited_list
    label: DNS nameservers
    description: Comma separated list of DNS nameservers for the private network.
    default: '8.8.8.8,8.8.4.4,10.110.15.1,10.110.15.2'

resources:
  network:
    type: lib/private_network.yaml    
    properties:
      public_network: { get_param: public_network }
      cidr: { get_param: cidr }
      dns: { get_param: dns_list }


  tiny_instance:
    type: lib/tiny.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key_pair }
      private_network: { get_attr: [network, name] }
      proxy_ip_port: { get_param: proxy_ip_port }

  floating_ip:
    type: lib/floating_ip.yaml
    properties:
      port: { get_attr: [tiny_instance, port] }
      public_network: { get_param: public_network }

outputs:
  ip:
    description: The public IP address to access the server.
    value: { get_attr: [floating_ip, ip] }
